version: "3"

services:
  web:
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: stackoverflow_clone_db
    image: postgres
    volumes:
      - stackoverflow_clone_db_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  stackoverflow_clone_db_data:
