name: testing

on:
  push:
  pull_request:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v2

      - name: run the tests
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml run web npm run test
